[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[rpc_endpoints]
# ETH goerli chain
eth_goerli = "https://goerli.infura.io/v3/6707728235da4599b4a045c1b40ff0d9" # Different API key.


eth_sepolia = "https://goerli.infura.io/v3/6707728235da4599b4a045c1b40ff0d9" # Different API key.


scroll_sepolia = "https://scroll-sepolia.public.blastapi.io" 


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
